platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

workspace 'TrustScience/TrustScience.xcworkspace'

def application_pods
  
end

def ui_pods
  
end

def core_pods
  
end


#### SeaTalk ####

target 'TrustScience' do
  project 'TrustScience/TrustScience/TrustScience.xcodeproj'
  application_pods()
  ui_pods()
  core_pods()
end

target 'TrustScienceUI' do
  project 'TrustScience/TrustScienceUI/TrustScienceUI.xcodeproj'
  ui_pods()
  core_pods()
end

target 'TrustScienceCore' do
  project 'TrustScience/TrustScienceCore/TrustScienceCore.xcodeproj'
  core_pods()
end

#### Post Install ####

post_install do |installer|

  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['ENABLE_BITCODE'] = 'NO'
          config.build_settings['DEBUG_INFORMATION_FORMAT'] = "dwarf-with-dsym"
          config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['$(inherited)']
      end
  end
end
